const imageGroups = {
    a: ['A/vggvhvkkj.png',
        'A/hgk.png',
        'A/Untitled-2-Recoveredhgfukh.png',
        'A/Untitled-2-Recoveredhgj.png',
        'A/Untitled-2-Recoveredhgu.png',
        'A/Untitled-2-Recoveredhjkvjk.png',
        'A/Untitled-2-RecoveredHKGC.png',
        'A/Untitled-2-Recoveredaerb.png',
        'A/Untitled-2-RecoveredAFGVB.png',
        'A/Untitled-2-RecoveredASJKBA.png',
        'A/Untitled-2-Recoveredbnchj.png',
        'A/Untitled-2-RecoveredCDSB.png',
        'A/Untitled-2-Recoveredcx,mvnxc.png',
        'A/Untitled-2-RecoveredDF.png',
        'A/Untitled-2-RecoveredDFBN,.png',
        'A/Untitled-2-RecoveredFDG.png',
        'A/Untitled-2-Recoveredfluy_.png',
        'A/Untitled-2-Recoveredgfjxk.png',
        'A/Untitled-2-Recoveredhckg.png',
        'A/Untitled-2-Recoveredhgfkhglj.png',
        'A/Untitled-2-RecoveredJBSCH.png',
        'A/Untitled-2-Recoveredjgfjk.png',
        'A/Untitled-2-Recoveredjh.png',
        'A/Untitled-2-Recoveredjkh.png',
        'A/Untitled-2-Recoveredjv.png',
        'A/Untitled-2-RecoveredKCJG.png',
        'A/Untitled-2-Recoveredkdsvj.png',
        'A/Untitled-2-Recoveredkhfdxk.png',
        'A/Untitled-2-Recoveredkjdzfv.png',
        'A/Untitled-2-Recoveredkjgklj.png',
        'A/Untitled-2-Recoveredkjv.png',
        'A/Untitled-2-RecoveredSDC.png',
        'A/Untitled-2-RecoveredSDKNBC.png',
        'A/Untitled-2-RecoveredSDLFHSDJFH.png',
        'A/Untitled-2-RecoveredSND.png',
        'A/Untitled-2-RecoveredSVD,NB.png',
        'A/Untitled-2-Recoveredvchf.png',
        'A/Untitled-2-Recoveredvf.png',
        'A/Untitled-2-RecoveredVHJ.png',
        'A/Untitled-2-Recoveredxdknfsd.png',
        'A/Untitled-2-Recoveredzdkfhj.png',
        'A/Untitled-2-Recoveredzdkfj.png',
        'A/Untitled-2-Recoveredzdkjf.png',
        'A/Untitled-2,B.png',
        'A/Untitled-2.png',
        'A/Untitled-2C.png',
        'A/Untitled-2FGIL.png',
        'A/Untitled-2FJ.png',
        'A/Untitled-2H.png',
        'A/Untitled-2HJG.png',
        'A/Untitled-2hkcg.png',
        'A/Untitled-2hkg.png',
        'A/Untitled-2JKGF.png',
        'A/Untitled-2JKL.png',
        'A/Untitled-2kgf.png',
        'A/Untitled-2KGVL.png',
        'A/Untitled-2kj.png',
        'A/Untitled-2KJCG.png',
        'A/Untitled-2kjhg.png',
        'A/Untitled-2kvj.png',
        'A/Untitled-2L.png',
        'A/Untitled-2vx.png',
        'A/Untitled-2MB.png',
        'A/Untitled-2SD.png',
        'A/Untitled-25.png',
        'A/vggvhvkkj.png',],
   b:  ['B/kjdv.png',
        'B/Untitled-2-Recoveredczbv.png',
        'B/Untitled-2-Recovereddssa.png',
        'B/Untitled-2-Recoveredfdg.png',
        'B/Untitled-2-Recoveredhgv.png',
        'B/Untitled-2-RecoveredJCG.png',
        'B/Untitled-2-RecoveredjSGDH_.png',
        'B/Untitled-2-Recoveredkhbjg.png',
        'B/Untitled-2-RecoveredKHCG.png',
        'B/Untitled-2-Recoveredmnkdf.png',
        'B/Untitled-2-RecoveredSA.png',
        'B/Untitled-2-RecoveredSAX.png',
        'B/Untitled-2-RecoveredSKVDA.png',
        'B/Untitled-2,MN.png',
        'B/Untitled-2.png',
        'B/Untitled-2GJH.png',
        'B/Untitled-2v.png',
        'B/Untitled-2yd.png',],
   c:  ['C/Untitled-2-Recovered,m.png',
        'C/Untitled-2-Recovered,zfvn.png',
        'C/Untitled-2-Recovered.png',
        'C/Untitled-2-Recoveredbdf.png',
        'C/Untitled-2-RecoveredBK.png',
        'C/Untitled-2-RecoveredDNSMC.png',
        'C/Untitled-2-RecoveredDSKJ.png',
        'C/Untitled-2-Recoveredhjlv.png',
        'C/Untitled-2-Recoveredhkg.png',
        'C/Untitled-2-RecoveredKHCG.png',
        'C/Untitled-2-Recoveredkhg.png',
        'C/Untitled-2-RecoveredKHGFHXH.png',
        'C/Untitled-2-Recoveredkjh.png',
        'C/Untitled-2-RecoveredKVJ.png',
        'C/Untitled-2-Recoveredl;.png',
        'C/Untitled-2-Recoverednmvj,b.png',
        'C/Untitled-2-RecoveredS,MNSD.png',
        'C/Untitled-2-Recovereds.png',
        'C/Untitled-2-RecoveredSCD.png',
        'C/Untitled-2-Recoveredsdjk.png',
        'C/Untitled-2-RecoveredSDNASLD.png',
        'C/Untitled-2-RecoveredVB.png',
        'C/Untitled-2-RecoveredZDF.png',
        'C/Untitled-2.png',
        'C/Untitled-2JHK.png',
        'C/Untitled-2kgchl.png',
        'C/Untitled-2KJGCJ.png',
        'C/Untitled-2ufo.png',
        'C/Untitled-299.png',],
    d: ['D/Untitled-2-Recoveredbdzfbf.png',
        'D/Untitled-2-Recoveredbfdz.png',
        'D/Untitled-2-Recoveredbgfs.png',
        'D/Untitled-2-RecoveredBSDF.png',
        'D/Untitled-2-Recovereddnmbvskjd.png',
        'D/Untitled-2-Recovereddnvmzf.png',
        'D/Untitled-2-Recovereddzfjkhg.png',
        'D/Untitled-2-Recoveredgfjdjh.png',
        'D/Untitled-2-Recoveredjh.png',
        'D/Untitled-2-Recoveredjhblk.png',
        'D/Untitled-2-Recoveredjhkgkjhvljk.png',
        'D/Untitled-2-Recoveredjohl.png',
        'D/Untitled-2-Recoveredkg.png',
        'D/Untitled-2-Recoveredmnvz.png',
        'D/Untitled-2-RecoveredNMSCDB.png',
        'D/Untitled-2-RecoveredSBCJVD.png',
        'D/Untitled-2-RecoveredSDMNBV.png',
        'D/Untitled-2-RecoveredVMNB.png',
        'D/Untitled-2-Recoveredxmzcjb.png',
        'D/Untitled-2-Recoveredzfdb.png',
        'D/Untitled-2cb.png',
        'D/Untitled-2FD.png',
        'D/Untitled-2hjc.png',
        'D/Untitled-2JH.png',
        'D/Untitled-2jhg.png',
        'D/Untitled-2KB.png',
        'D/Untitled-2LCJLH.png',],
    e: ['E/cmnvbzslkj.png',
        'E/CSDNB.png',
        'E/F.png',
        'E/HVL.png',
        'E/Untitled-2-Recovered,jhk.png',
        'E/Untitled-2-Recovered;kajDBCSDV.png',
        'E/Untitled-2-Recovered.png',
        'E/Untitled-2-Recoveredasd.png',
        'E/Untitled-2-Recoveredbdf.png',
        'E/Untitled-2-Recoveredbdgz.png',
        'E/Untitled-2-Recoveredbk.png',
        'E/Untitled-2-Recoveredbvcjh.png',
        'E/Untitled-2-Recoveredcb.png',
        'E/Untitled-2-RecoveredCMVD.png',
        'E/Untitled-2-Recoveredcxvbmnxc.png',
        'E/Untitled-2-RecoveredDFKJHDS.png',
        'E/Untitled-2-Recovereddfljh.png',
        'E/Untitled-2-Recovereddfzkn.png',
        'E/Untitled-2-RecoveredDNKVV.png',
        'E/Untitled-2-RecoveredDSMN.png',
        'E/Untitled-2-RecoveredEAGR.png',
        'E/Untitled-2-RecoveredFBMN.png',
        'E/Untitled-2-RecoveredFGS.png',
        'E/Untitled-2-Recoveredgb.png',
        'E/Untitled-2-Recoveredgvhjkglk.png',
        'E/Untitled-2-RecoveredHGVL.png',
        'E/Untitled-2-Recoveredhjgfjhg.png',
        'E/Untitled-2-Recoveredhkcg.png',
        'E/Untitled-2-Recoveredjgvk.png',
        'E/Untitled-2-Recoveredjhcfl.png',
        'E/Untitled-2-Recoveredjhk.png',
        'E/Untitled-2-RecoveredJHV.png',
        'E/Untitled-2-Recoveredjk.png',
        'E/Untitled-2-Recoveredkgjhfjh.png',
        'E/Untitled-2-Recoveredjkhgvkjl.png',
        'E/Untitled-2-RecoveredKHGC.png',
        'E/Untitled-2-Recoveredkj.png',
        'E/Untitled-2-Recoveredkjchbvk.png',
        'E/Untitled-2-Recoveredkljdsv.png',
        'E/Untitled-2-Recoveredklkjhcv.png',
        'E/Untitled-2-Recoveredkvkjh_.png',
        'E/Untitled-2-RecoveredLJHV.png',
        'E/Untitled-2-Recoveredlkl;.png',
        'E/Untitled-2-Recoveredlkzsf.png',
        'E/Untitled-2-RecoveredMCBN.png',
        'E/Untitled-2-RecoveredMFNAV.png',
        'E/Untitled-2-RecoveredNB.png',
        'E/Untitled-2-RecoveredNBVX.png',
        'E/Untitled-2-Recoverednkxv.png',
        'E/Untitled-2-RecoveredSBNDC.png',
        'E/Untitled-2-RecoveredSBNDV.png',
        'E/Untitled-2-RecoveredSCDMN.png',
        'E/Untitled-2-RecoveredSCDVB.png',
        'E/Untitled-2-Recoveredsdcs.png',
        'E/Untitled-2-RecoveredSDMBNN.png',
        'E/Untitled-2-RecoveredSNVMB.png',
        'E/Untitled-2-Recoveredsrt.png',
        'E/Untitled-2-RecoveredSSDDAS.png',
        'E/Untitled-2-Recoveredvcxjk.png',
        'E/Untitled-2-Recoveredtfdfkj.png',
        'E/Untitled-2-Recoveredxfg.png',
        'E/Untitled-2-Recoveredzdfb.png',
        'E/Untitled-2-Recoveredzdfkjv.png',
        'E/Untitled-2.,.png',
        'E/Untitled-2.png',
        'E/Untitled-2bvc.png',
        'E/Untitled-2cghk.png',
        'E/Untitled-2gfhd.png',
        'E/Untitled-2gfx.png',
        'E/Untitled-2hkcgl.png',
        'E/Untitled-2IU.png',
        'E/Untitled-2jgklk.png',
        'E/Untitled-2JHBK.png',
        'E/Untitled-2JHK.png',
        'E/Untitled-2JHL.png',
        'E/Untitled-2jk.png',
        'E/Untitled-2jkg.png',
        'E/Untitled-2KHK;H.png',
        'E/Untitled-2kj.png',
        'E/Untitled-2KX.png',
        'E/Untitled-2ljhkkj.png',
        'E/Untitled-2LXG.png',
        'E/Untitled-2LXOY.png',
        'E/Untitled-2m.png',
        'E/Untitled-2MN.png',
        'E/Untitled-2nbv.png',
        'E/Untitled-2nbvk.png',
        'E/Untitled-2nmnvbncm.png',
        'E/Untitled-2SDAV.png',
        'E/Untitled-2VC.png',
        'E/Untitled-2VH.png',
        'E/xfgjkl.png',],
    f: ['F/Untitled-2-RecoveredBNA.png',
        'F/Untitled-2-RecoveredDFGS.png',
        'F/Untitled-2-RecoveredDSN.png',
        'F/Untitled-2-Recoveredhfdkhgghj.png',
        'F/Untitled-2-Recoveredkdjf.png',
        'F/Untitled-2-Recoveredksjdbfs.png',
        'F/Untitled-2-RecoveredNSD.png',
        'F/Untitled-2-Recoveredzdfb.png',
        'F/Untitled-2.png',
        'F/Untitled-2JH.png',
        'F/Untitled-2kjg.png',
        'F/Untitled-2kjh b.png',],
    g: ['G/hj.png',
        'G/Untitled-2-RecoveredALSDNASC.png',
        'G/Untitled-2-RecoveredDFBJV.png',
        'G/Untitled-2-RecoveredDFMNB.png',
        'G/Untitled-2-RecoveredDSCNM.png',
        'G/Untitled-2-Recovereddskjhckjs.png',
        'G/Untitled-2-Recoveredgfd.png',
        'G/Untitled-2-Recoveredhvj.png',
        'G/Untitled-2-RecoveredKNDFBS.png',
        'G/Untitled-2-Recoveredlkjhb.png',
        'G/Untitled-2-Recoveredsdf.png',
        'G/Untitled-2-Recoveredsrtyh.png',
        'G/Untitled-2-Recoveredvzdfl.png',
        'G/Untitled-2.png',
        'G/Untitled-2ghcjk.png',
        'G/Untitled-2HG.png',
        'G/Untitled-2JKHJ.png',
        'G/Untitled-2lhjg.png',
        'G/Untitled-2lk.png',],
    h: ['H/Untitled-2-Recovered rge.png',
        'H/Untitled-2-Recoveredbxfg.png',
        'H/Untitled-2-RecoveredCSN.png',
        'H/Untitled-2-RecoveredDFKLJS.png',
        'H/Untitled-2-RecoveredDSC.png',
        'H/Untitled-2-Recovereddsv.png',
        'H/Untitled-2-RecoveredFDMBN.png',
        'H/Untitled-2-Recoveredjkgjhg.png',
        'H/Untitled-2-Recoveredjvh.png',
        'H/Untitled-2-Recoveredkhgfkjh.png',
        'H/Untitled-2-RecoveredKLJFDASD.png',
        'H/Untitled-2-Recoveredmj.png',
        'H/Untitled-2-RecoveredMNBC.png',
        'H/Untitled-2-Recoverednfgdnk.png',
        'H/Untitled-2-RecoveredNSFGS.png',
        'H/Untitled-2-Recoveredsdcsd.png',
        'H/Untitled-2-RecoveredSDMNB.png',
        'H/Untitled-2-RecoveredSX.png',
        'H/Untitled-2-RecoveredXCMN.png',
        'H/Untitled-2-Recoveredznfg.png',
        'H/Untitled-2.png',
        'H/Untitled-2ADSF.png',
        'H/Untitled-2BJ.png',
        'H/Untitled-2df.png',
        'H/Untitled-2jhc.png',
        'H/Untitled-2JHK.png',
        'H/Untitled-2KCG.png',
        'H/Untitled-2kgjv.png',
        'H/Untitled-2KJ.png',
        'H/Untitled-2lknb.png',
        'H/Untitled-2M.png',],
    i: ['I/fdysgjhklg.png',
        'I/SD.png',
        'I/SDLHJV.png',
        'I/Untitled-2-Recovered.png',
        'I/Untitled-2-Recoveredabyre.png',
        'I/Untitled-2-RecoveredBV.png',
        'I/Untitled-2-Recovereddjkfz.png',
        'I/Untitled-2-Recovereddksj.png',
        'I/Untitled-2-RecoveredDSSAD.png',
        'I/Untitled-2-Recoveredew.png',
        'I/Untitled-2-RecoveredFDBNM.png',
        'I/Untitled-2-Recoveredhgk.png',
        'I/Untitled-2-Recoveredhjgfkhj.png',
        'I/Untitled-2-Recoveredhvckhgj.png',
        'I/Untitled-2-Recoveredjgfkj.png',
        'I/Untitled-2-Recoveredjkgfkjh.png',
        'I/Untitled-2-RecoveredJLBSD.png',
        'I/Untitled-2-Recoveredjvkg.png',
        'I/Untitled-2-Recoveredkhgc.png',
        'I/Untitled-2-Recoveredkjjhgjhkjhg.png',
        'I/Untitled-2-Recoveredkl.png',
        'I/Untitled-2-RecoveredKNSDBC.png',
        'I/Untitled-2-Recoveredmb.png',
        'I/Untitled-2-RecoveredMNDSC.png',
        'I/Untitled-2-Recoverednb.png',
        'I/Untitled-2-RecoveredNJDBVS.png',
        'I/Untitled-2-Recoverednmsvdz.png',
        'I/Untitled-2-Recoverednxfg.png',
        'I/Untitled-2-Recoveredreag.png',
        'I/Untitled-2-RecoveredSDBFB.png',
        'I/Untitled-2-Recoveredugfukl.png',
        'I/Untitled-2-RecoveredV.png',
        'I/Untitled-2-Recoveredxgjk.png',
        'I/Untitled-2.png',
        'I/Untitled-2DFS.png',
        'I/Untitled-2F.png',
        'I/Untitled-2hcjg.png',
        'I/Untitled-2HGV.png',
        'I/Untitled-2hjgc.png',
        'I/Untitled-2jgkc.png',
        'I/Untitled-2JK.png',
        'I/Untitled-2jkgf.png',
        'I/Untitled-2JKWQER.png',
        'I/Untitled-2jvhkgh.png',
        'I/Untitled-2KGV.png',
        'I/Untitled-2kjcg.png',
        'I/Untitled-2KJH.png',
        'I/Untitled-2klhj.png',
        'I/Untitled-2LCJ.png',
        'I/Untitled-2MN,.png',
        'I/Untitled-2U.png',
        'I/Untitled-2VB.png',
        'I/Untitled-2VC.png',
        'I/Untitled-25.png',],
    j: ['J/Untitled-2-Recovered.png',
        'J/Untitled-2-RecoveredDFSG.png',
        'J/Untitled-2-RecoveredFDSA.png',],
    k: ['K/fsW.png',
        'K/Untitled-2-Recovered.png',
        'K/Untitled-2-RecoveredA,N.png',
        'K/Untitled-2-Recovereddzfb.png',
        'K/Untitled-2-RecoveredFSGKNB.png',
        'K/Untitled-2-Recoveredhj.png',
        'K/Untitled-2-Recoveredhkgc.png',
        'K/Untitled-2-Recoveredkgjvjkgh.png',
        'K/Untitled-2-RecoveredSCDN.png',
        'K/Untitled-2-RecoveredSDKFBS.png',
        'K/Untitled-2-Recoveredsr].png',],
    l: ['L/ave.png',
        'L/DDFGA.png',
        'L/DF.png',
        'L/kg.png',
        'L/Untitled-2-Recoveredbare.png',
        'L/Untitled-2-RecoveredBMSDC.png',
        'L/Untitled-2-RecoveredCDMNBS.png',
        'L/Untitled-2-Recovereddfzg.png',
        'L/Untitled-2-RecoveredDSBMN.png',
        'L/Untitled-2-RecoveredDSNB.png',
        'L/Untitled-2-Recoveredfhdgj_.png',
        'L/Untitled-2-Recoveredgh.png',
        'L/Untitled-2-Recoveredhgf.png',
        'L/Untitled-2-Recoveredjhkhl.png',
        'L/Untitled-2-Recoveredjvkjgj.png',
        'L/Untitled-2-RecoveredKGK.png',
        'L/Untitled-2-RecoveredKJVG.png',
        'L/Untitled-2-Recoveredlkbkjj.png',
        'L/Untitled-2-RecoveredM,CDN.png',
        'L/Untitled-2-Recoveredzbdf.png',
        'L/Untitled-2-Recoveredzdfv.png',
        'L/Untitled-2,BN.png',
        'L/Untitled-2;L.png',
        'L/Untitled-2.png',
        'L/Untitled-2cfhj.png',
        'L/Untitled-2CV.png',
        'L/Untitled-2jcfh.png',
        'L/Untitled-2jhjkjhvj.png',
        'L/Untitled-2kg.png',
        'L/Untitled-2kghc.png',
        'L/Untitled-2KLJ.png',
        'L/Untitled-2vbnjkhjg.png',
        'L/vfkS.png',
        'L/xfgn.png',],
    m: ['M/Untitled-2-Recovered sg.png',
        'M/Untitled-2-Recovered,msv.png',
        'M/Untitled-2-Recoveredbjk.png',
        'M/Untitled-2-Recovereddf,nmgvd,fmv.png',
        'M/Untitled-2-RecoveredDSBC.png',
        'M/Untitled-2-RecoveredDSNVBASD.png',
        'M/Untitled-2-Recovereddssas.png',
        'M/Untitled-2-RecoveredJGXF.png',
        'M/Untitled-2-RecoveredJV.png',
        'M/Untitled-2-Recoveredm,xnvcx.png',
        'M/Untitled-2-RecoveredMNBFG.png',
        'M/Untitled-2-Recoverednb.png',
        'M/Untitled-2-RecoveredVF.png',
        'M/Untitled-2.png',
        'M/Untitled-2FDS.png',
        'M/Untitled-2hgk.png',
        'M/Untitled-2jk.png',
        'M/Untitled-2KJFG.png',],
    n: ['N/GFD.png',
        'N/hgkdkgfj.png',
        'N/jlgh.png',
        'N/nm.png',
        'N/Untitled-2-Recovered.png',
        'N/Untitled-2-Recoveredaewrterh.png',
        'N/Untitled-2-RecoveredASXJ.png',
        'N/Untitled-2-Recoveredbsf.png',
        'N/Untitled-2-RecoveredCMNV.png',
        'N/Untitled-2-RecoveredDAFG.png',
        'N/Untitled-2-RecoveredDFSKNLL.png',
        'N/Untitled-2-RecoveredDMNFBSDFA.png',
        'N/Untitled-2-Recovereddsczs.png',
        'N/Untitled-2-Recovereddvf.png',
        'N/Untitled-2-RecoveredF.png',
        'N/Untitled-2-Recoveredjgc.png',
        'N/Untitled-2-Recoveredjgfkhjgj.png',
        'N/Untitled-2-Recoveredjh.png',
        'N/Untitled-2-Recoveredjkf.png',
        'N/Untitled-2-Recoveredjkh.png',
        'N/Untitled-2-Recoveredk.png',
        'N/Untitled-2-Recoveredkdnfj.png',
        'N/Untitled-2-Recoveredkjsdhakjs.png',
        'N/Untitled-2-RecoveredKJVHD.png',
        'N/Untitled-2-Recoveredlk.png',
        'N/Untitled-2-Recoveredmn_.png',
        'N/Untitled-2-Recoverednm.png',
        'N/Untitled-2-RecoveredSAC.png',
        'N/Untitled-2-Recoveredsdc.png',
        'N/Untitled-2-Recoveredsdmnf.png',
        'N/Untitled-2-RecoveredVDMNBVMD.png',
        'N/Untitled-2-Recoveredvjdkbkjfs.png',
        'N/Untitled-2-Recoveredvmnbcxm,zx.png',
        'N/Untitled-2-Recoveredzdfk.png',
        'N/Untitled-2.png',
        'N/Untitled-2GK.png',
        'N/Untitled-2hgjf.png',
        'N/Untitled-2KGH.png',
        'N/Untitled-2khg.png',
        'N/Untitled-2khv.png',
        'N/Untitled-2kjg.png',
        'N/Untitled-2KK.png',
        'N/Untitled-2M.png',
        'N/Untitled-2VNG.png',
        'N/Untitled-2XD.png',],
    o: ['O/DAD.png',
        'O/hv.png',
        'O/Untitled-2-Recovered,mm.png',
        'O/Untitled-2-Recoveredadfb.png',
        'O/Untitled-2-RecoveredAWTVEr.png',
        'O/Untitled-2-Recoveredb,smdn.png',
        'O/Untitled-2-RecoveredDCSVGH.png',
        'O/Untitled-2-Recovereddfzb.png',
        'O/Untitled-2-Recovereddghf.png',
        'O/Untitled-2-RecoveredDJFBSVLDF.png',
        'O/Untitled-2-RecoveredDMNVBALS.png',
        'O/Untitled-2-RecoveredDSBNV.png',
        'O/Untitled-2-Recovereddsc.png',
        'O/Untitled-2-RecoveredDSK.png',
        'O/Untitled-2-RecoveredDSKNSC.png',
        'O/Untitled-2-Recovereddsvvsd.png',
        'O/Untitled-2-RecoveredDVMNBD.png',
        'O/Untitled-2-Recovereddzfjkh.png',
        'O/Untitled-2-RecoveredFGNSFG.png',
        'O/Untitled-2-RecoveredGRZS.png',
        'O/Untitled-2-Recoveredgxbdfz.png',
        'O/Untitled-2-RecoveredHGJ.png',
        'O/Untitled-2-Recoveredjdsvsjk.png',
        'O/Untitled-2-Recoveredjk.png',
        'O/Untitled-2-Recoveredjkkk.png',
        'O/Untitled-2-RecoveredKCG.png',
        'O/Untitled-2-Recoveredkfngjkdhg.png',
        'O/Untitled-2-Recoveredkj.png',
        'O/Untitled-2-Recoveredkjhg.png',
        'O/Untitled-2-Recoveredkjsdhvkjsd.png',
        'O/Untitled-2-Recoveredm.png',
        'O/Untitled-2-RecoveredNSD.png',
        'O/Untitled-2-RecoveredSAIJDOF.png',
        'O/Untitled-2-RecoveredSCKJ.png',
        'O/Untitled-2-RecoveredSCM,D.png',
        'O/Untitled-2-RecoveredSDGDF.png',
        'O/Untitled-2-RecoveredSDMN.png',
        'O/Untitled-2-RecoveredSDNBV.png',
        'O/Untitled-2-Recoveredsdsa.png',
        'O/Untitled-2-Recoveredskv.png',
        'O/Untitled-2-RecoveredVDF.png',
        'O/Untitled-2-RecoveredVDFN.png',
        'O/Untitled-2-Recoveredwrhnjr.png',
        'O/Untitled-2-Recoveredxngfx.png',
        'O/Untitled-2-RecoveredZDBF.png',
        'O/Untitled-2,M.png',
        'O/Untitled-2.png',
        'O/Untitled-2DF.png',
        'O/Untitled-2HJG.png',
        'O/Untitled-2JG.png',
        'O/Untitled-2jkg.png',
        'O/Untitled-2JKHKHG.png',
        'O/Untitled-2KG.png',
        'O/Untitled-2khg.png',
        'O/Untitled-2lgh.png',
        'O/Untitled-2ljhv.png',
        'O/Untitled-2M.png',
        'O/Untitled-2MB.png',
        'O/Untitled-2U.png',
        'O/Untitled-2Y.png',],
    p: ['P/Untitled-2-Recoveredaskv.png',
        'P/Untitled-2-Recovereddfb.png',
        'P/Untitled-2-Recoveredjh.png',
        'P/Untitled-2-Recoveredkhj.png',
        'P/Untitled-2-Recoveredkjhg.png',
        'P/Untitled-2-Recoverednj.png',
        'P/Untitled-2-RecoveredSDLFNS.png',
        'P/Untitled-2.png',
        'P/Untitled-2CKH.png',
        'P/Untitled-2GXHF.png',
        'P/Untitled-2JK.png',
        'P/Untitled-2JKH.png',
        'P/Untitled-2KC.png.png',
        'P/Untitled-2UL.png',
        'P/Untitled-2VK.png',],
    r: ['R/dsg.png',
        'R/sg.png',
        'R/Untitled-2-Recoveredavkf.png',
        'R/Untitled-2-RecoveredBSDFB.png',
        'R/Untitled-2-RecoveredDAFG.png',
        'R/Untitled-2-RecoveredDCNBSDNMC.png',
        'R/Untitled-2-RecoveredDFGS.png',
        'R/Untitled-2-RecoveredDFVBNV.png',
        'R/Untitled-2-RecoveredDMNBVDMFV.png',
        'R/Untitled-2-RecoveredDSCMN.png',
        'R/Untitled-2-Recoveredfgbdzs.png',
        'R/Untitled-2-Recoveredgfhxh.png',
        'R/Untitled-2-Recoveredhgvfkjhhl.png',
        'R/Untitled-2-Recoveredhkcg.png',
        'R/Untitled-2-RecoveredJH.png',
        'R/Untitled-2-Recoveredjkvhvds.png',
        'R/Untitled-2-RecoveredJLH.png',
        'R/Untitled-2-Recoveredjthf_.png',
        'R/Untitled-2-Recoveredkdj.png',
        'R/Untitled-2-Recoveredkjll.png',
        'R/Untitled-2-Recoveredkjsdf.png',
        'R/Untitled-2-RecoveredKJSDFSDMNF.png',
        'R/Untitled-2-RecoveredKLFBD.png',
        'R/Untitled-2-RecoveredNB.png',
        'R/Untitled-2-Recoverednjbvjkhghkj.png',
        'R/Untitled-2-Recovereds,nfsdklj.png',
        'R/Untitled-2-Recoveredsd,mnf.png',
        'R/Untitled-2-RecoveredSDJK.png',
        'R/Untitled-2-RecoveredSDN.png',
        'R/Untitled-2-Recoveredsdv.png',
        'R/Untitled-2-RecoveredVDMNBVSND.png',
        'R/Untitled-2-RecoveredSKLADF.png',
        'R/Untitled-2-Recoveredvjk.png',
        'R/Untitled-2-Recoveredzlksfjhgz.png',
        'R/Untitled-2-Recoveredzsdkjh.png',
        'R/Untitled-2.png',
        'R/Untitled-2B_.png',
        'R/Untitled-2FGD.png',
        'R/Untitled-2GF.png',
        'R/Untitled-2HCK.png',
        'R/Untitled-2HJ.png',
        'R/Untitled-2HJIO_.png',
        'R/Untitled-2jhc.png',
        'R/Untitled-2JKHL.png',
        'R/Untitled-2KCH.png',
        'R/Untitled-2kj.png',
        'R/Untitled-2KL.png',
        'R/Untitled-2L;.png',
        'R/Untitled-2LCJ.png',
        'R/Untitled-2N.png',
        'R/Untitled-2vcx.png',
        'R/Untitled-2567.png',],
    s: ['S/HCFXGH.png',
        'S/Untitled-2-Recovered N.png',
        'S/Untitled-2-Recoveredcjg.png',
        'S/Untitled-2-Recovereddzf.png',
        'S/Untitled-2-Recoveredflskdjhf.png',
        'S/Untitled-2-Recoveredhgvk.png',
        'S/Untitled-2-Recoveredhjgfkjh.png',
        'S/Untitled-2-Recoveredhkgc.png',
        'S/Untitled-2-Recoveredjghkl_.png',
        'S/Untitled-2-Recoveredjk.png',
        'S/Untitled-2-Recoveredjkhv.png',
        'S/Untitled-2-Recoveredjxhfl.png',
        'S/Untitled-2-Recoveredkfx.png',
        'S/Untitled-2-RecoveredKJCX.png',
        'S/Untitled-2-RecoveredKJVG.png',
        'S/Untitled-2-Recoveredkkj.png',
        'S/Untitled-2-Recoveredkl.png',
        'S/Untitled-2-RecoveredMNBV.png',
        'S/Untitled-2-Recoverednfgs.png',
        'S/Untitled-2-Recoveredsdg.png',
        'S/Untitled-2-RecoveredSMBN.png',
        'S/Untitled-2-RecoveredVF.png',
        'S/Untitled-2-Recoveredvxljchsjkd.png',
        'S/Untitled-2-RecoveredZDFS.png',
        'S/Untitled-2-Recoveredzfdb.png',
        'S/Untitled-2.png',
        'S/Untitled-2BV.png',
        'S/Untitled-2C.png',
        'S/Untitled-2DS.png',
        'S/Untitled-2F.png',
        'S/Untitled-2GH.png',
        'S/Untitled-2GY.png',
        'S/Untitled-2jgkc.png',
        'S/Untitled-2kgj.png',
        'S/Untitled-2KHJ.png',
        'S/Untitled-2lfh.png',
        'S/Untitled-2LHJL.png',
        'S/Untitled-2lhkj.png',
        'S/Untitled-2VD.png',],
    t: ['T/Untitled-2-Recovered,mzdv.png',
        'T/Untitled-2-RecoveredCDSBJ.png',
        'T/Untitled-2-Recovereddflkjg.png',
        'T/Untitled-2-RecoveredDJNVBAS.png',
        'T/Untitled-2-Recovereddkjnf.png',
        'T/Untitled-2-RecoveredDKJSAFL.png',
        'T/Untitled-2-RecoveredDNMF.png',
        'T/Untitled-2-RecoveredDSBVN.png',
        'T/Untitled-2-RecoveredDZKFNJBV.png',
        'T/Untitled-2-Recoveredg.png',
        'T/Untitled-2-Recoveredgbzf.png',
        'T/Untitled-2-Recoveredghjfkjhl.png',
        'T/Untitled-2-Recoveredh.png',
        'T/Untitled-2-Recoveredhfx.png',
        'T/Untitled-2-Recoveredhgdxkl.png',
        'T/Untitled-2-Recoveredj.png',
        'T/Untitled-2-RecoveredJFGC.png',
        'T/Untitled-2-RecoveredJGV.png',
        'T/Untitled-2-Recoveredjhkge.png',
        'T/Untitled-2-Recoveredjhkjg.png',
        'T/Untitled-2-Recoveredjkh.png',
        'T/Untitled-2-RecoveredJKHDVF.png',
        'T/Untitled-2-Recoveredkk.png',
        'T/Untitled-2-Recoveredkxjvskjd.png',
        'T/Untitled-2-Recoveredliygkugfhj_.png',
        'T/Untitled-2-Recoveredm.png',
        'T/Untitled-2-RecoveredMNCV.png',
        'T/Untitled-2-Recoverednbv.png',
        'T/Untitled-2-Recoverednvv.png',
        'T/Untitled-2-Recovereds th.png',
        'T/Untitled-2-RecoveredSA,CA.png',
        'T/Untitled-2-RecoveredSDBC.png',
        'T/Untitled-2-RecoveredSDCNM.png',
        'T/Untitled-2-RecoveredSLDJKBA;S.png',
        'T/Untitled-2-RecoveredSLKJDB;a.png',
        'T/Untitled-2-Recoveredsndbsdj.png',
        'T/Untitled-2-RecoveredVBH.png',
        'T/Untitled-2-Recoveredvcjh.png',
        'T/Untitled-2-RecoveredXC,M.png',
        'T/Untitled-2-Recoveredxnvbzlkd.png',
        'T/Untitled-2-Recoveredzdfb.png',
        'T/Untitled-2.png',
        'T/Untitled-2B,NV.png',
        'T/Untitled-2BVC.png',
        'T/Untitled-2cxzv.png',
        'T/Untitled-2GF.png',
        'T/Untitled-2GJK;.png',
        'T/Untitled-2hj.png',
        'T/Untitled-2J.png',
        'T/Untitled-2JHBL.png',
        'T/Untitled-2jhg.png',
        'T/Untitled-2JHGC.png',
        'T/Untitled-2JLHLJ.png',
        'T/Untitled-2khg.png',
        'T/Untitled-2KJCJL.png',
        'T/Untitled-2kjg.png',
        'T/Untitled-2LCU.png',
        'T/Untitled-2LK.png',
        'T/Untitled-2MBN.png',
        'T/Untitled-2MNB.png',
        'T/Untitled-2N.png',
        'T/Untitled-2nbmn.png',
        'T/Untitled-2SA.png',],
    u: ['U/Untitled-2-RecoveredCG.png',
        'U/Untitled-2-RecoveredDMNC.png',
        'U/Untitled-2-RecoveredDMNV.png',
        'U/Untitled-2-Recovereddzfgg.png',
        'U/Untitled-2-Recoveredhjg.png',
        'U/Untitled-2-Recoveredjhblk.png',
        'U/Untitled-2-Recoveredkj.png',
        'U/Untitled-2-RecoveredKJV.png',
        'U/Untitled-2-Recoveredsdkjfhs.png',
        'U/Untitled-2-RecoveredSDNM.png',
        'U/Untitled-2-RecoveredSJH.png',
        'U/Untitled-2-RecoveredSMNBVALS.png',
        'U/Untitled-2-Recoveredvcknbxk.png',
        'U/Untitled-2-Recoveredzfbd.png',
        'U/Untitled-2-Recoveredzvk.png',
        'U/Untitled-2.png',
        'U/Untitled-2DF.png',
        'U/Untitled-2HJG.png',
        'U/Untitled-2KJ.png',
        'U/Untitled-2UYI.png',],
    v: ['V/Untitled-2-Recoveredbnv.png',
        'V/Untitled-2-Recoveredfkdnj.png',
        'V/Untitled-2-RecoveredHV.png',
        'V/Untitled-2-Recoveredhvjkhhl.png',
        'V/Untitled-2-Recovereds.png',
        'V/Untitled-2-RecoveredSDMBC.png',
        'V/Untitled-2-Recoveredzdfv.png',
        'V/Untitled-2.png',
        'V/Untitled-2jkv.png',
        'V/Untitled-2klj.png',],
    w: ['W/Untitled-2-Recoveredabyer.png',
        'W/Untitled-2-RecoveredDSMN.png',
        'W/Untitled-2-Recoveredkchg.png',
        'W/Untitled-2-RecoveredKJ.png',
        'W/Untitled-2-Recoveredkn.png',
        'W/Untitled-2-Recoveredsdcsd.png',
        'W/Untitled-2-RecoveredVMBN.png',
        'W/Untitled-2-Recoveredxgfdz.png',
        'W/Untitled-2.png',
        'W/Untitled-2hj.png',
        'W/Untitled-2JHF.png',
        'W/Untitled-2JHG.png',
        'W/Untitled-2MN.png',
        'W/Untitled-2N;.png',
        'W/Untitled-J.png',],
    x: ['X/Untitled-2-Recovered.png',],
    y: ['Y/Untitled-2-Recovered.png',
        'Y/Untitled-2-Recoveredasc.png',
        'Y/Untitled-2-Recoveredbjkzfdh.png',
        'Y/Untitled-2-Recoveredbsfg.png',
        'Y/Untitled-2-Recovereddbfzjk.png',
        'Y/Untitled-2-RecoveredDFGA.png',
        'Y/Untitled-2-Recovereddfz.png',
        'Y/Untitled-2-Recovereddsjk.png',
        'Y/Untitled-2-Recoveredhgjck_.png',
        'Y/Untitled-2-RecoveredHGL.png',
        'Y/Untitled-2-Recoveredhjfjh.png',
        'Y/Untitled-2-Recoveredj.png',
        'Y/Untitled-2-Recoveredjkvjkh.png',
        'Y/Untitled-2-Recoveredkcgh.png',
        'Y/Untitled-2-Recoveredknjvx.png',
        'Y/Untitled-2-Recoveredn.png',
        'Y/Untitled-2-RecoveredS,DMNA.png',
        'Y/Untitled-2-Recovereds.png',
        'Y/Untitled-2-RecoveredSAKVH.png',
        'Y/Untitled-2-RecoveredVF.png',
        'Y/Untitled-2-Recoveredzdfb.png',
        'Y/Untitled-2,MN.png',
        'Y/Untitled-2.png',
        'Y/Untitled-2jkh.png',
        'Y/Untitled-2KBJV.png',
        'Y/Untitled-2kghc.png',
        'Y/Untitled-2MNL.png',
        'Y/Untitled-2NBV.png',
        'Y/Untitled-2njbv.png',
        'Y/Untitled-2586.png',],
};

const usedImages = []; // Track used images
const imageContainer = document.getElementById('imageContainer');
let randomPositioningEnabled = false; // Toggle for random positioning

// Create a temporary input field
const tempInput = document.createElement('input');
tempInput.style.position = 'absolute';
tempInput.style.opacity = '0'; // Make it invisible
tempInput.style.pointerEvents = 'none'; // Prevent interactions
document.body.appendChild(tempInput);

// Function to render a random image based on the provided letter
function renderRandomImage(letter) {
    const images = imageGroups[letter];
    if (images) {
        // Filter out already used images
        const availableImages = images.filter(image => !usedImages.includes(image));

        if (availableImages.length > 0) {
            const newImage = document.createElement('img');
            const randomImage = availableImages[Math.floor(Math.random() * availableImages.length)];
            newImage.src = randomImage;
            newImage.className = 'image';

            if (randomPositioningEnabled) {
                // Random positioning
                const x = Math.random() * (window.innerWidth - 100);
                const y = Math.random() * (window.innerHeight - 100);
                newImage.style.position = 'absolute';
                newImage.style.left = `${x}px`;
                newImage.style.top = `${y}px`;
            }

            imageContainer.appendChild(newImage);
            usedImages.push(randomImage); // Mark this image as used
        }
    }
}

// Function to remove the last image
function removeLastImage() {
    const images = imageContainer.getElementsByTagName('img');
    if (images.length > 0) {
        const lastImage = images[images.length - 1];
        imageContainer.removeChild(lastImage); // Remove the last image
        usedImages.pop(); // Remove the last image from the usedImages array
    }
}

// Function to clear the image container
function clearImageContainer() {
    imageContainer.innerHTML = ''; // Remove all images
    usedImages.length = 0; // Clear the usedImages array
}

// Insert a blank space
function insertBlankSpace() {
    const blankSpace = document.createElement('div');
    blankSpace.className = 'blank-space'; // You can style this if needed
    blankSpace.style.width = '100px'; // Set width for the blank space
    blankSpace.style.height = '100px'; // Set height for the blank space
    blankSpace.style.display = 'inline-block'; // Align with images
    imageContainer.appendChild(blankSpace);
}

// Event listener for screen taps
document.addEventListener('touchstart', function(event) {
    tempInput.style.pointerEvents = 'auto'; // Enable interactions
    tempInput.focus(); // Focus on the input field to trigger the keyboard

    // Listen for input events on the temporary input field
    tempInput.addEventListener('input', function() {
        const inputValue = tempInput.value;

        // Clear previous images
        clearImageContainer();

        // Render images for each letter in the input value
        for (const letter of inputValue) {
            if (letter.trim() !== '') { // Skip if it's just whitespace
                renderRandomImage(letter.toLowerCase());
            } else {
                insertBlankSpace(); // Insert a blank space for spaces
            }
        }
    });

    // Handle input loss when the keyboard closes
    tempInput.addEventListener('blur', function() {
        tempInput.value = ''; // Clear the input value
        clearImageContainer(); // Optionally clear images when keyboard closes
        tempInput.style.pointerEvents = 'none'; // Disable interactions
    });
});

// Event listener for the backspace key
document.addEventListener('keydown', function(event) {
    if (event.key === 'Backspace') {
        event.preventDefault(); // Prevent default backspace behavior
        removeLastImage(); // Remove the last image
    }
});

// Toggle random positioning on button click
document.getElementById('togglePosition').addEventListener('click', function() {
    randomPositioningEnabled = !randomPositioningEnabled; // Toggle the variable
    this.textContent = randomPositioningEnabled ? 'Disable Random Positioning' : 'Enable Random Positioning'; // Update button text
});

// Set Day Mode
document.getElementById('dayMode').addEventListener('click', function() {
    document.body.classList.remove('night-mode'); // Ensure night mode is removed
    imageContainer.classList.remove('night-mode'); // Ensure image container is in day mode
});

// Set Night Mode
document.getElementById('nightMode').addEventListener('click', function() {
    document.body.classList.add('night-mode'); // Add night mode class
    imageContainer.classList.add('night-mode'); // Add night mode class to image container
});

// Event listener for the Clear Images button
document.getElementById('clearContainer').addEventListener('click', clearImageContainer);